AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation for creating Lambda functions and API Gateway
 
Resources:
  dynamodbHandler:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: arn:aws:iam::401985591036:role/LabRole
      Runtime: nodejs20.x
      Code:
        S3Bucket: dalvacationhome-lambda
        S3Key: message-passing.zip